version: "3.9"
services:
  backend:
    build: ./ms-portafolio
    container_name: portafolio-back
    ports:
      - "8000:8000"
    networks:
      - portafolio-net

  frontend:
    build: ./portafolio-front
    container_name: portafolio-front
    ports:
      - "5173:5173"
    environment:
      VITE_BACKEND_URL: "http://backend:8000"
    networks:
      - portafolio-net
    depends_on:
      - backend

networks:
  portafolio-net:
    driver: bridge
